import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Explicit sidebar structure for BruControl documentation.
 * All planned pages are linked; no autogenerated sections for major areas.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    'features',
    'requirements',
    'quick-start',
    {
      type: 'category',
      label: 'Hardware',
      items: [
        'hardware/overview',
        'hardware/device-types',
        'hardware/wiring-maps',
        'hardware/control-system',
        'hardware/firmware-installation',
        'hardware/interface-setup',
      ],
    },
    {
      type: 'category',
      label: 'Application',
      items: [
        'application/overview',
        'application/setup',
        'application/workspaces',
        'application/settings',
        'application/updates-releases',
        'application/data-views',
        'application/file-manager',
        'application/log-viewer',
      ],
    },
    {
      type: 'category',
      label: 'Solution Explorer',
      items: [
        'solution-explorer/overview',
        'solution-explorer/tree-structure',
        'solution-explorer/folders',
        'solution-explorer/context-menu',
        'solution-explorer/add-elements',
      ],
    },
    {
      type: 'category',
      label: 'Dashboard',
      items: [
        'dashboard/overview',
        'dashboard/canvas-layout',
        'dashboard/zoom-pan',
        'dashboard/tool-mode',
        'dashboard/element-appearance',
      ],
    },
    {
      type: 'category',
      label: 'Elements',
      items: [
        'elements/overview',
        {
          type: 'category',
          label: 'Non-Device',
          items: [
            'elements/global-variable',
            'elements/toggle-switch',
            'elements/button',
            'elements/generic',
            'elements/timer',
            'elements/alarm',
            'elements/script',
            'elements/chart',
            'elements/profile',
          ],
        },
        {
          type: 'category',
          label: 'Device',
          items: [
            'elements/device-elements-overview',
            'elements/digital-output',
            'elements/digital-input',
            'elements/duty-cycle',
            'elements/pwm-output',
            'elements/analog-input',
            'elements/counter',
            'elements/ow-temp',
            'elements/spi-sensor',
            'elements/hydrometer',
            'elements/hysteresis',
            'elements/pid',
            'elements/deadband',
          ],
        },
        {
          type: 'category',
          label: 'Calibrations',
          items: [
            'elements/calibrations-overview',
            'elements/calibration-types',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Element Templates',
      items: [
        'element-templates/overview',
        'element-templates/element-template-developer-guide',
        'element-templates/templates',
        'element-templates/custom-properties',
        'element-templates/default-templates',
        'element-templates/element-template-editor',
        'element-templates/plugin-store',
      ],
    },
    {
      type: 'category',
      label: 'Scripting',
      items: [
        'scripting/introduction',
        'scripting/sections',
        'scripting/variables',
        'scripting/element-properties',
        'scripting/conditionals',
        'scripting/flow-control',
        'scripting/examples',
        'scripting/syntax-reference',
      ],
    },
    {
      type: 'category',
      label: 'Mocking',
      items: [
        'mocking/overview',
        'mocking/mock-mode',
        'mocking/mock-page',
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [
        'api/overview',
        'api/workspace-api',
        'api/element-apis',
        'api/device-api',
        'api/process-api',
        'api/settings-api',
        'api/misc-apis',
      ],
    },
    {
      type: 'category',
      label: 'Appendix',
      items: [
        'appendix/overview',
        'appendix/troubleshooting',
        'appendix/winc1500-wifi',
        'appendix/troubleshooting-network',
        'appendix/technical-assistance',
        'appendix/interface-overview',
        'appendix/interface-specific',
      ],
    },
  ],
};

export default sidebars;
