import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Main documentation sidebar
  docsSidebar: [
    'intro',
    'features',
    'requirements',
    'quick-start',
    {
      type: 'category',
      label: 'Hardware',
      items: [
        'hardware/overview',
        'hardware/device-types',
        'hardware/wiring-maps',
        'hardware/control-system',
        'hardware/firmware-installation',
      ],
    },
    {
      type: 'category',
      label: 'Application',
      items: [
        {
          type: 'autogenerated',
          dirName: 'application',
        },
      ],
    },
    {
      type: 'category',
      label: 'Elements',
      items: [
        {
          type: 'autogenerated',
          dirName: 'elements',
        },
      ],
    },
    {
      type: 'category',
      label: 'Scripting',
      items: [
        'scripting/introduction',
        'scripting/sections',
        'scripting/variables',
        {
          type: 'autogenerated',
          dirName: 'scripting',
        },
      ],
    },
    {
      type: 'category',
      label: 'Appendix',
      items: [
        {
          type: 'autogenerated',
          dirName: 'appendix',
        },
      ],
    },
  ],
};

export default sidebars;
